sudo: false
dist: trusty
language: elixir
elixir:
  - 1.4.1
  - 1.5.3
otp_release:
  - 18.2.1
  - 20.3
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
    - _deps
    - _build
env:
  global:
    - DATABASE_URL=ecto://postgres:@localhost/bourne
script:
  - mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    recipients:
      - m.t.williams@live.com
    on_success: change
    on_failure: change
